export const CLASSIFICATION_BATCH_DEFAULT_LIMIT = 10;
export const CLASSIFICATION_BATCH_MIN_LIMIT = 1;
export const CLASSIFICATION_BATCH_MAX_LIMIT = 500;
export const CLASSIFICATION_BATCH_LIMIT_ERROR = `Limit must be between ${CLASSIFICATION_BATCH_MIN_LIMIT} and ${CLASSIFICATION_BATCH_MAX_LIMIT}.`;
