export const OPENALEX_INGESTION_DEFAULT_LIMIT = 10;
export const OPENALEX_INGESTION_MIN_LIMIT = 1;
export const OPENALEX_INGESTION_MAX_LIMIT = 500;
export const OPENALEX_INGESTION_CONCURRENCY = 8;
export const OPENALEX_REQUEST_MAX_LIMIT = 100;
